name: Extract Boot Image Files
on:
  push:
    branches: [ main ]

jobs:
  extract_boot_files:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Install JDK
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Install Dependencies
        run: |
          sudo apt-get update && sudo apt-get install -y git unzip wget
      - name: Clone mktool repository
        run: |
          git clone https://github.com/GameTheory-/mktool.git
      - name: Make mktool executable
        run: |
          cd mktool
          chmod +x run.sh
      - name: Extract Boot Image
        run: |
          cd mktool
          wget https://bashupload.com/IHCfg/boot.img -O boot.img
          ./run.sh unpackbootimg boot.img
      - name: Extract Ramdisk Files
        run: |
          # Extract the contents of the RAM disk image
          cd mktool
          gunzip initramfs.cpio.gz
          mkdir initramfs
          cd initramfs
          cpio -i < ../initramfs.cpio
          # The extracted files will be in the initramfs directory
