name: OZIP Extractor

on:
  push:
    branches: [ main ]
  schedule:
    - cron: '0 0 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Download OZIP
      run: |
        sudo apt-get update
        sudo apt-get install -y aria2
        aria2c https://assorted.downloads.oppo.com/firmware/CPH1723/M6763A_11_OTA_0450_all_T6tah4NhiqWo.ozip
    - name: Decrypt OZIP
      run: |
        sudo apt-get update
        sudo apt-get install -y python3-pip zip
        sudo pip3 install setuptools wheel docopt pycryptodome
        wget https://raw.githubusercontent.com/techyminati/oppo_ozip_decrypt/master/ozipdecrypt.py
        python3 ozipdecrypt.py M6763A_11_OTA_0450_all_T6tah4NhiqWo.ozip
    - name: Extract boot.img
      run: |
        sudo apt-get update
        sudo apt-get install -y unzip
        unzip -l M6763A_11_OTA_0450_all_T6tah4NhiqWo.zip
        if unzip -q M6763A_11_OTA_0450_all_T6tah4NhiqWo.zip boot.img; then mv boot.img extracted_boot.img; fi
    - name: Extract recovery.img
      run: |
        sudo apt-get update
        sudo apt-get install -y unzip
        unzip -l M6763A_11_OTA_0450_all_T6tah4NhiqWo.zip
        if unzip -q M6763A_11_OTA_0450_all_T6tah4NhiqWo.zip recovery.img; then mv recovery.img extracted_recovery.img; fi
    - name: Upload Extracted Files
      run: |
        curl -s https://apiv2.gofile.io/getServer | jq  -r '.data|.server' > server.txt
        SERVER=$(cat server.txt)
        UPLOAD=$(curl -F file=@extracted_boot.img https://${SERVER}.gofile.io/uploadFile)
        LINK=$(echo $UPLOAD | jq -r '.data|.downloadPage')
        echo "Boot Image: $LINK"
        UPLOAD=$(curl -F file=@extracted_recovery.img https://${SERVER}.gofile.io/uploadFile)
        LINK=$(echo $UPLOAD | jq -r '.data|.downloadPage')
        echo "Recovery Image: $LINK"
